### ISSUE TITLE
Consider breaking up org.openrewrite.java.spring.cloud2022.MigrateCloudSleuthToMicrometerTracing to have separate code changes vs dependency changes

### ISSUE THREAD

**Issue by iparadiso** [openrewrite/rewrite-spring#381] opened 2023-06-26 21:03 UTC
[org.openrewrite.java.spring.cloud2022.MigrateCloudSleuthToMicrometerTracing](https://github.com/openrewrite/rewrite-spring/blob/b80cd59ddca2330319c36f8aec85605be35938fc/src/main/resources/META-INF/rewrite/spring-cloud-2022.yml#L88) is a pretty great rewrite rule, but it causes dependency resolution issues for some gradle users.  Namely, it leaves dependency versions where some users would want versions to be taken from a BOM, or supply other libraries that transitively pull in the other micrometer and spring dependencies.  

Having a partial rule for code/config changes and dependency changes would allow users to not have to copy and modify this entire recipe to update their own dependency rule changes.

**Comment by timtebeek** [comment] 2023-06-28 10:43
Hi @iparadiso ; thanks for chiming in here! Could you describe which unwanted changes you're seeing exactly? Maybe even as a unit test to fit into [MigrateCloudSleuthToMicrometerTracingTest](https://github.com/openrewrite/rewrite-spring/blob/main/src/test/java/org/openrewrite/java/spring/cloud2022/MigrateCloudSleuthToMicrometerTracingTest.java) ? That way we can (also) try to fix any unwanted side effects.

You described excess dependency versions, which we might be able to fix similar to how we already have
https://github.com/openrewrite/rewrite-spring/blob/b80cd59ddca2330319c36f8aec85605be35938fc/src/main/resources/META-INF/rewrite/spring-cloud-2022.yml#L157-L160

I'm also not opposed to splitting up [MigrateCloudSleuthToMicrometerTracing](https://github.com/openrewrite/rewrite-spring/blob/b80cd59ddca2330319c36f8aec85605be35938fc/src/main/resources/META-INF/rewrite/spring-cloud-2022.yml#L88) into for instance
1. MigrateCloudSleuthToMicrometerTracingDependencies
2. MigrateCloudSleuthToMicrometerTracingClasses
3. MigrateCloudSleuthToMicrometerTracingProperties

That way you should be able to selectively apply changes as needed, although ideally we fix the underlying issue such that it's not needed to think through which recipes to run.

**Comment by timtebeek** [comment] 2024-08-12 18:07
Closing as likely caused by an earlier issue with not correctly handling managed/transitive dependencies likely now solved. That removes the need to split these up, as we've lacked input since.

**Closed by timtebeek** 2024-08-12 18:07 UTC
Labels: bug, good first issue
