### ISSUE TITLE
UpgradeSpringBoot_3_0 Recipe does not upgrade dependency versions in Gradle build file

### ISSUE THREAD

**Issue by JeremyTwiggs** [openrewrite/rewrite-spring#349] opened 2023-05-03 15:07 UTC
Hi,

I've been trying to upgrade a Spring Boot 2.7.11 project to 3.0.x.

The versions of Spring Boot and Spring Cloud are not updated when I run the UpgradeSpringBoot_3_0 recipe.

I see that the spring-boot-30.yml does includes MavenPomUpgrade in it's recipeListl, but I don't see anything for gradle.

Thanks.

**Comment by timtebeek** [comment] 2023-05-03 15:17
Hi @JeremyTwiggs ! You're right; we're still working on [bringing Gradle dependency upgrades to parity with Maven dependency upgrades](https://github.com/openrewrite/rewrite-spring/issues/288). We're working on this at the moment, and might end up adding a single agnostic recipe that will handle both, rather than a recipe each for Maven and Gradle.

**Comment by Jenson3210** [comment] 2023-05-19 19:31
@timtebeek, Coming back to our session we had earlier today @ Spring IO, I assume this is the reason why it the example was not working for the gradle project?

**Comment by timtebeek** [comment] 2023-05-21 11:23
Yes likely so! I'm hoping #228 get's resolved quickly, such that we better support both Maven and Gradle for the same migrations.

**Comment by Jenson3210** [comment] 2023-06-03 15:40
> Yes likely so! I'm hoping #228 get's resolved quickly, such that we better support both Maven and Gradle for the same migrations.

For reference: I think the issue you meant to refer to: #288

**Comment by Jenson3210** [comment] 2023-06-08 06:17
@timtebeek As I mentioned to Chris earlier, I would be happy to help out here. 
Do I understand it correctly, that in order to do this: 

- Alter all related recipes on [recipes repo](https://github.com/openrewrite/rewrite-spring/tree/main/src/main/resources/META-INF/rewrite) to use new recipe
- [publish them locally](https://docs.openrewrite.org/authoring-recipes/recipe-development-environment#local-publishing-for-testing)
- run them against some of our codebases
- provide feedback. 

What I do not see atm is how to run/adapt/create the test cases for this new behaviour as the maven adaptation today also seem untested (or i am missing something [here](https://github.com/openrewrite/rewrite-spring/tree/main/src/test/java/org/openrewrite/java/spring)).

**Comment by timtebeek** [comment] 2023-06-08 07:18
That indeed sounds like the steps to take. We have some, but not a lot of tests for the dependency upgrades in rewrite-spring; you can typically recognize these through their use of [`pomXml(...)`](https://github.com/search?q=repo%3Aopenrewrite%2Frewrite-spring%20pomxml&type=code). Since these are declarative recipes that reuse recipes from openrewrite/rewrite, they are usually [extensively tested elsewhere](https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeDependencyVersionTest.java#L38). So in essence here it's swapping the Maven / Gradle specific recipes for the generic ones, removing duplicates and, verifying things still mostly work as expected.

**Comment by timtebeek** [comment] 2023-06-09 09:12
It appears @kunli2 already did a first pass at changing these dependency upgrades from Maven only to both Maven and Gradle in https://github.com/openrewrite/rewrite-spring/commit/5e90a83ebedf970800cdb4719f46852bb132a40d , which should be available in rewrite-spring versions [v5.0.0](https://github.com/openrewrite/rewrite-spring/releases/tag/v5.0.0) and [v4.36.1](https://github.com/openrewrite/rewrite-spring/releases/tag/v4.36.1). The MavenPomUpgrade that was mentioned here initially has [also received that update](https://github.com/openrewrite/rewrite-spring/blame/c4e1fa998faae854a2f1f833466824d110901436/src/main/resources/META-INF/rewrite/spring-boot-30.yml#L56).

So I'm inclined to think this issue has already been solved, and will thus close the issue.
Feel free to correct me if I'm wrong in thinking this now works as expected for Gradle as well!

**Closed by timtebeek** 2023-06-09 09:12 UTC
Labels: duplicate

**Comment by Jenson3210** [comment] 2023-06-10 23:48
@timtebeek 

I tried this recipe locally once. 
As this is my first usage, I might be doing something wrong.

**Preparation**

However, for me something is not working migrating the a7439c7 commit of [spring-petclinic](https://github.com/spring-projects/spring-petclinic/tree/a7439c74ea718c4f59fe6c7c643c4afe59d7e718) as this is the one showcased during demo (but this is the first commit with gradle)

Besides the fact that the documentation sent me into long debugging times ending up in version incompatibility caused by me only taking the newest version for BOM and not plugin as docs still point to old versions. EG. 
- [old versions 1](https://docs.openrewrite.org/reference/latest-versions-of-every-openrewrite-module)
- [old versions 2](https://docs.openrewrite.org/running-recipes/getting-started)

After fixing the versions I ended up with following build gradle input: 
```groovy
plugins {
  id 'org.springframework.boot' version '2.6.1'
  id 'io.spring.dependency-management' version '1.0.11.RELEASE'
  id 'java'
  id 'org.openrewrite.rewrite' version '6.0.0'
}

rewrite {
    activeRecipe(
            'org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_0',
    )
}

//...
dependencies {
  rewrite platform('org.openrewrite.recipe:rewrite-recipe-bom:2.0.0')
  rewrite('org.openrewrite.recipe:rewrite-spring')
  implementation 'org.springframework.boot:spring-boot-starter-cache'
  //...
  runtimeOnly 'org.ehcache:ehcache'
  runtimeOnly 'com.h2database:h2'
  runtimeOnly 'mysql:mysql-connector-java'
}
```

**RUNNING**

I then launched `gradle rewriteRun`. 
Build succeeded. (except for #371 errors still showing, fixed with upcoming version I assume)

**RESULTS**

The plugin versions are not adapted.
```groovy
plugins {
  id 'org.springframework.boot' version '2.6.1' // <-- Version not adapted
  id 'io.spring.dependency-management' version '1.0.11.RELEASE' // <-- Version not adapted
  //...
}
//...
dependencies {
  //...
  runtimeOnly 'org.ehcache:ehcache' // <-- not found for gradle refresh dependencies as spring bom removed ehcache it seems ('org.ehcache:ehcache:3.7.1')
  runtimeOnly 'com.h2database:h2'
  runtimeOnly 'mysql:mysql-connector-java'  // <-- not found for gradle refresh dependencies as new version is 'com.mysql:mysql-connector-j'
}
```

**Running application locally**
Startup fails `JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE vets ( id INTEGER [*]IDENTITY PRIMARY KEY`. 
Fixed it for demo (and I also believe should not be fixed as part of openRewrite as one should still know what he is doing in his/her app) by removing the IDENTITY word in the sql.
After manually adapting all the changes mentioned above, I have it running locally retrieving vets.

Should i raise this spring boot 3 migration issue as separate issue as the main issue is also in gradle build file?
Do you agree that for the h2 migrations inside the BOM a developer should "know" this or be able to get help on the matter within his/her team?

**Comment by timtebeek** [comment] 2023-06-12 12:55
Hi @Jenson3210 ; thank you for the detailed report! I think at this stage separate issues would indeed be best, to make these easier to track & fix. Some might be relatively easy, whereas others might need a closer look.

To give an example: you mention that `mysql:mysql-connector-java` is not updated for Gradle projects; that's unfortunate, and likely easily fixed; we already have handling to rename to `mysql-connector-j` for Maven:
https://github.com/openrewrite/rewrite-spring/blob/f0151affbff68d4c6538540ae4fe605ecabc0c2e/src/main/resources/META-INF/rewrite/spring-boot-27.yml#L54-L59
This we could likely convert over to also handle Gradle through [the generic ChangeDependency](https://github.com/openrewrite/rewrite-java-dependencies/blob/main/src/main/java/org/openrewrite/java/dependencies/ChangeDependency.java).

We might need similar handling as we already have for `mysql-connector-j` applied to `ehcache`, as that also saw it's version number no longer managed, as you've pointed out. There might be more to it (adopting an alternative), but at least adding the version number should restore functionality post-migration for now.

Not sure about changing the plugin version numbers; perhaps also best tackled separately as we're already looking into improving Gradle support, and this could be part of that work.

Hope we're able to tackle these items separately for you soon!
